services:
  store_manager_app:
    build: .
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: mydb
      MONGODB_HOST: mongo
      DB_USERNAME: user
      DB_PASSWORD: pass
    stdin_open: true
    tty: true

  mysql:
    image: mysql:8
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppass"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
