name: MongoDB Test

on: [push, pull_request]

jobs:
  test-mongo:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        env:
          MONGO_INITDB_ROOT_USERNAME: user
          MONGO_INITDB_ROOT_PASSWORD: pass
          MONGO_INITDB_DATABASE: store_manager
        ports:
          - 27017:27017
        volumes:
          - ./db-init:/docker-entrypoint-initdb.d

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install mongosh
        run: |
          curl -fsSL https://pgp.mongodb.com/server-6.0.asc | sudo tee /etc/apt/trusted.gpg.d/mongodb-server-6.0.asc
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh

      - name: Wait for MongoDB
        run: |
          for i in {1..10}; do
            mongosh "mongodb://user:pass@127.0.0.1:27017/admin" --eval "db.adminCommand('ping')" && break
            echo "Waiting for MongoDB..."
            sleep 5
          done

      - name: Run MongoDB test
        working-directory: ./src
        run: python -m pytest -v test_mongo_connection.py
